[package]
name = "greet-async"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.46.0"
futures-util = "0.3.31"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
