[package]
name = "ping-mdns-flood"
version = "0.1.0"
authors = ["hwipl"]
edition = "2024"

[dependencies]
# use current git version dated 2026-01-07 to remove lru dependency for dependabot alert
libp2p = { git = "https://github.com/libp2p/rust-libp2p", rev = "5e3519fb66b92c7f7c0dc744ab360fd8b669fe54", features = ["tokio", "mdns", "tcp", "tls", "noise", "yamux", "dns", "macros", "floodsub", "mdns"] }
futures = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
serde_cbor = "0.11.2"
tokio = "1.49.0"
